name: Setup
description: Download and load Docker image artifact

runs:
  using: composite
  steps:
    - name: Download Docker artifact
      uses: actions/download-artifact@v8
      with:
        name: openipe-docker
        path: /tmp

    - name: Load Docker image
      shell: bash
      run: docker load --input /tmp/openipe-docker.tar
