#!/bin/bash

# Enable/Disable waveform dumping
OMSP_NODUMP=0
export OMSP_NODUMP

# Choose GCC toolchain prefix ('msp430' for MSPGCC / 'msp430-elf' for GCC RedHat/TI)
# Note: default to MSPGCC until GCC RedHat/TI is mature enough
if command -v msp430-gcc >/dev/null; then
    MSPGCC_PFX=msp430
else
    MSPGCC_PFX=msp430-elf
fi
#MSPGCC_PFX=msp430-elf
export MSPGCC_PFX

# Choose simulator:
#                   - iverilog  : Icarus Verilog  (default)
#                   - cver      : CVer
#                   - verilog   : Verilog-XL
#                   - ncverilog : NC-Verilog
#                   - vcs       : VCS
#                   - vsim      : Modelsim
#                   - isim      : Xilinx simulator
OMSP_SIMULATOR=iverilog
export OMSP_SIMULATOR

rm -rf cov_work

# Cleanup from previous regression
LOG_DIR=./log
rm -rf $LOG_DIR/*
mkdir -p $LOG_DIR

export __IPE_SIM=1

# IPE register behavior
../bin/msp430sim ipe/ipe_noflag | tee $LOG_DIR/ipe_noflag.log
../bin/msp430sim ipe/ipe_incorrect_pointer | tee $LOG_DIR/ipe_incorrect_pointer.log
../bin/msp430sim ipe/ipe_correct_pointer | tee $LOG_DIR/ipe_correct_pointer.log
../bin/msp430sim ipe/ipe_existing_pointer | tee $LOG_DIR/ipe_existing_pointer.log
../bin/msp430sim ipe/ipe_locked_registers | tee $LOG_DIR/ipe_locked_registers.log
../bin/msp430sim ipe/ipe_changing_registers | tee $LOG_DIR/ipe_changing_registers.log
../bin/msp430sim ipe/ipe_inside_access | tee $LOG_DIR/ipe_inside_access.log

# Protecting IPE region against software
../bin/msp430sim ipe/ipe_sw_read | tee $LOG_DIR/ipe_sw_read.log
../bin/msp430sim ipe/ipe_sw_write | tee $LOG_DIR/ipe_sw_write.log
../bin/msp430sim ipe/ipe_sw_jump | tee $LOG_DIR/ipe_sw_jump.log

# Protecting the firmware against software
../bin/msp430sim ipe/firmware_sw_write | tee $LOG_DIR/firmware_sw_write.log
../bin/msp430sim ipe/firmware_sw_jump | tee $LOG_DIR/firmware_sw_jump.log

# Protecting IPE region against the debugger
../bin/msp430sim ipe/ipe_dbg_read | tee $LOG_DIR/ipe_dbg_read.log
../bin/msp430sim ipe/ipe_dbg_write | tee $LOG_DIR/ipe_dbg_write.log
../bin/msp430sim ipe/ipe_dbg_halt | tee $LOG_DIR/ipe_dbg_halt.log

# Protecting the firmware against the debugger
../bin/msp430sim ipe/firmware_dbg_write | tee $LOG_DIR/firmware_dbg_write.log
__IPE_IRQ_FW=1 ../bin/msp430sim ipe/firmware_dbg_halt -firmware ../src/ipe/bootcode-fw-irq.s43 | tee $LOG_DIR/firmware_dbg_halt.log

# Preventing attacks
../bin/msp430sim ipe/attack_ccc | tee $LOG_DIR/attack_ccc.log
../bin/msp430sim ipe/attack_irq_exploit | tee $LOG_DIR/attack_irq_exploit.log
../bin/msp430sim ipe/attack_malicious_reti | tee $LOG_DIR/attack_malicious_reti.log
../bin/msp430sim ipe/attack_nmi_handler | tee $LOG_DIR/attack_nmi_handler.log
__IPE_IRQ_FW=1 ../bin/msp430sim ipe/attack_firmware_rop -firmware ../src/ipe/bootcode-fw-irq.s43 | tee $LOG_DIR/attack_firmware_rop.log

# Disable random DMA accesses for DMA tests
unset __IPE_SIM

# Protecting the IPE region against DMA reads/writes
../bin/msp430sim ipe/ipe_dma_read | tee $LOG_DIR/ipe_dma_read.log
../bin/msp430sim ipe/ipe_dma_write | tee $LOG_DIR/ipe_dma_write.log

# Protecting the firmware against DMA writes
../bin/msp430sim ipe/firmware_dma_write | tee $LOG_DIR/firmware_dma_write.log

export __IPE_SIM=1

# Use case: SW-based secure interrupts
__IPE_IRQ_SW=1 ../bin/msp430sim ipe/case-study/sw_irq | tee $LOG_DIR/sw_irq.log

# Use case: FW-based secure interrupts with Nemesis mitigation
__IPE_IRQ_FW=1 ../bin/msp430sim -firmware ../src/ipe/bootcode-fw-irq.s43 ipe/case-study/fw_irq | tee $LOG_DIR/fw_irq.log
__IPE_IRQ_FW=1 ../bin/msp430sim -firmware ../src/ipe/bootcode-fw-irq.s43 ipe/case-study/fw_irq_nemesis | tee $LOG_DIR/fw_irq_nemesis.log

# Report regression results
../bin/parse_results $LOG_DIR

FIRST_RES=$?

rm -rf cov_work

# Cleanup from previous regression
LOG_DIR=./log
rm -rf $LOG_DIR/*
mkdir -p $LOG_DIR

# Running attacks without the hardware fixes (expected to succeed and thus cause violations)
export __OMIT_IPE_FIXES=1
export __OMIT_SP_SWITCHING=1
../bin/msp430sim ipe/ipe_sw_jump | tee $LOG_DIR/ipe_sw_jump.log
../bin/msp430sim ipe/attack_ccc | tee $LOG_DIR/attack_ccc.log
../bin/msp430sim ipe/attack_irq_exploit | tee $LOG_DIR/attack_irq_exploit.log

# Report regression results
../bin/parse_results $LOG_DIR

if [ $? -ne 3 ] || [ $FIRST_RES -ne 0 ]; then
    exit 1
fi
