OPENIPE         = ../framework
CC              = $(OPENIPE)/compiler.py
LD              = $(OPENIPE)/linker.py

CPU             = MSP430F149

INCLUDE         = -I$(OPENIPE)
CFLAGS          = -Wall -std=gnu99 -g -mmcu=$(CPU) -mhwmult=none -D__$(CPU)__ 
LDFLAGS         = -mmcu=$(CPU) -mhwmult=none -T pmem.x
